profile_name = nv-redshift-developer-datalake
region = eu-north-1
sso_account_id = 726406984899
sso_region = eu-west-1
sso_role_name = DataAnalyst
sso_start_url = https://northvolt.awsapps.com/start#/


 


profile_name = nv-datalake
region = eu-north-1
sso_account_id = 726406984899
sso_region = eu-west-1
sso_role_name = DataAnalyst
sso_start_url = https://northvolt.awsapps.com/start#/
