host='jdbc:redshift://eu-north-1-aws-datalake-data-platform-redshift.czoml5r2boyw.eu-north-1.redshift.amazonaws.com:5439/datawarehouse'
database='darawarehouse'
port=5439,
user='admin',
password='my_password'

